spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${PROD_DATABASE_URL}
    username: ${PROD_DATABASE_USERNAME}
    password: ${PROD_DATABASE_PASSWORD}
  jwt:
    secret-key: ${PROD_JWT_SECRET_KEY}

  data:
    redis:
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT}

  auth:
    success-redirect-url: ${PROD_KAKAO_SUCCESS_REDIRECT_URL}
    kakao:
      client-id: ${PROD_KAKAO_CLIENT_ID}
      redirect-uri: ${PROD_KAKAO_REDIRECT_URI}