spring:
  application:
    name: connectrip_be
  profiles:
    active: local

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      location: /usr/share/temp
      max-file-size: 30MB
      max-request-size: 30MB

  jwt:
    access-token-expiration-time: 1800000
    refresh-token-expiration-time: 604800000

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
