spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}            # 배포용 DB 주소를 환경 변수로 관리
    username: ${DB_USERNAME}  # DB 사용자 이름
    password: ${DB_PASSWORD}  # DB 비밀번호

  data:
    redis:
      host: ${REDIS_HOST}     # 배포 환경용 Redis 주소
      port: 6379

# 환경 변수로 관리되는 값들:
# DB_USERNAME, DB_PASSWORD
# REDIS_HOST, REDIS_PASSWORD
# AWS_ACCESS_KEY, AWS_SECRET_KEY
