spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time-zone: UTC
    show-sql: true
  jwt:
    secret-key: ${DEV_JWT_SECRET_KEY}

  auth:
    success-redirect-url: ${DEV_KAKAO_SUCCESS_REDIRECT_URL}
    kakao:
      client-id: ${DEV_KAKAO_CLIENT_ID}
      redirect-uri: ${DEV_KAKAO_REDIRECT_URI}