spring:
  application:
    name: connectrip_be
  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jwt:
    access-token-expiration-time: 1800000
    refresh-token-expiration-time: 604800000

# 추후 local, dev, prod 분리
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
