spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${LOCAL_DATABASE_URL}
    username: ${LOCAL_DATABASE_USERNAME}
    password: ${LOCAL_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time-zone: UTC
    show-sql: true
  jwt:
    secret-key: ${LOCAL_JWT_SECRET_KEY}

  auth:
    success-redirect-url: ${LOCAL_KAKAO_SUCCESS_REDIRECT_URL}
    kakao:
      client-id: ${LOCAL_KAKAO_CLIENT_ID}
      redirect-uri: ${LOCAL_KAKAO_REDIRECT_URI}